# Generated by Django 5.2.4 on 2025-07-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='Credential_URL',
            field=models.URLField(blank=True, max_length=20),
        ),
    ]
