# Generated by Django 5.2.4 on 2025-07-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certification_credential_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='Credential_URL',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
