# Generated by Django 5.2.4 on 2025-07-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_certification_credential_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='Credential_URL',
            new_name='credential_url',
        ),
    ]
